# docker pull ubuntu:latest
# # compute expand storage /usr/libexec/oci-growfs [-y] [-n] [-h | --help]

---
- name: Install Bitcoin Core
  hosts: localhost

  tasks:
  - name: Create /var/bitcoin directory for variable files - bitcoin data directory
    ansible.builtin.file:
       path:  /var/bitcoin/
       state: directory
       mode: '0755'

  - name: Create /var/bitcoin directory for binary files
    ansible.builtin.file:
       path:  /usr/local/btc/
       state: directory
       mode: '0755'       
       
  - name: Install the latest version of sudo
    ansible.builtin.apt:
      name: sudo
      state: latest       
       
  - name: Install the latest version of jq
    ansible.builtin.apt:
      name: jq
      state: latest     
  
  - name: Install the latest version of libssl1.0-dev
    ansible.builtin.apt:
      name: libssl-dev
      state: latest
      
  - name: Install the latest version of gcc
    ansible.builtin.apt:
      name: gcc
      state: latest 

  - name: Install the latest version of curl
    ansible.builtin.apt:
      name: curl
      state: latest    

  - name: Install the latest version of wget
    ansible.builtin.apt:
      name: gcc
      state: latest       
            
  - name: Ensure group Coin group exists
    ansible.builtin.group:
      name: coin
      state: present

  - name: Ensure group Coin group exists
    ansible.builtin.group:
      name: wheel
      state: present
      
  - name: Add the user token with a bash shell, appending the group coin and wheel to the user's groups
    ansible.builtin.user:
      name: token
      shell: /bin/bash
      groups: coin,wheel
      append: yes

  - name: Download and unarchive Bitcoin Core
    ansible.builtin.unarchive:
       src: https://bitcoincore.org/bin/bitcoin-core-24.0.1/bitcoin-24.0.1-x86_64-linux-gnu.tar.gz
       dest: /usr/local/
       remote_src: yes

  - name: Download Rust installation script
    ansible.builtin.get_url:
      url: https://sh.rustup.rs 
      dest: /tmp/rustup-init.sh
      mode: '0755'
      
  - name: install rust/cargo
    become: true
    become_method: su
    become_user: token
    ansible.builtin.shell: /tmp/rustup-init.sh -y
      
  - name: Install the latest version of git
    ansible.builtin.apt:
      name: git
      state: latest
      
  - name: Clone Greg Ord
    ansible.builtin.git:
      repo: https://github.com/gmart7t2/ord.git
      dest: /usr/local/btc/ordg
      version: master   

  - name: Clone Casey Ord 
    ansible.builtin.git:
      repo: https://github.com/casey/ord.git
      dest: /usr/local/btc/ord
      version: master    
      
  - name: Recursively change ownership of /var/bitcoin to token:coin
    ansible.builtin.file:
      path: /var/bitcoin
      state: directory
      recurse: yes
      owner: token
      group: coin 

  - name: Recursively change ownership of /usr/local/btc to token:coin
    ansible.builtin.file:
      path: /usr/local/btc
      state: directory
      recurse: yes
      owner: token
      group: coin 
      
  - name: compile Casey Ord - this takes some time
    become: true
    become_method: su
    become_user: token
    ansible.builtin.shell: 
       executable: /bin/bash
       chdir: /usr/local/btc/ord
       cmd: source $HOME/.cargo/env |~/.cargo/bin/cargo build --release
       
  - name: compile Greg Ord - this takes some time
    become: true
    become_method: su
    become_user: token
    ansible.builtin.shell: 
       executable: /bin/bash
       chdir: /usr/local/btc/ordg
       cmd: source $HOME/.cargo/env |~/.cargo/bin/cargo build --release
       
  - name: update user path
    become: true
    become_method: su
    become_user: token
    ansible.builtin.shell: 
       executable: /bin/bash
       cmd: echo "export PATH=$PATH:/usr/local/btc/ordg/target/release:/usr/local/btc/ord/target/release" >> ~/.bash_profile

  - name: rename greg ord to ordg
    become: true
    become_method: su
    become_user: token
    ansible.builtin.shell: 
      executable: /bin/bash
      cmd: mv /usr/local/btc/ordg/target/release/ord /usr/local/btc/ordg/target/release/ordg
      
  #- name: Download Ordinal Index No Sats - Embedded RustDB
  #  ansible.builtin.get_url:
  #    url: https://
  #    dest: /bitcoindata/
  #    mode: '0755'
      
  # - name: Download Ordinal Index With Sats - 84+GB - Embedded RustDB
  #   ansible.builtin.get_url:
  #     url: https://
  #     dest: /bitcoin/data/
  #    mode: '0755'

  # - name: Download Latest Bitcoin Blocks
  #   ansible.builtin.get_url:
  #     url: https://
  #     dest: /bitcoin/data/
  #    mode: '0755'

  # - name: Download Latest Bitcoin txindex
  #   ansible.builtin.get_url:
  #     url: https://
  #     dest: /bitcoin/data/
  #    mode: '0755'